sensor:
{
  # 充电时 (AC)：整体偏亮，且更早达到高亮度
  ac_regression_points = [ 0.10, 0.25, 0.60, 0.75, 0.75, 0.75, 0.80, 0.80, 0.85, 0.95, 1.0 ];

  # 电池时 (BATT)：整体亮度降低，最高限制在 75%，保留环境光梯度
  batt_regression_points = [ 0.05, 0.12, 0.20, 0.28, 0.38, 0.48, 0.55, 0.62, 0.68, 0.72, 0.75 ];

  # 如果你的笔记本有独立环境光传感器 (ALS)，填入设备名可绕过摄像头。
  # 如果留空则默认按摄像头 -> ALS 的顺序自动寻找。
  # devname = "/dev/vedio0"; 

  captures = [ 5, 5 ];
};

backlight:
{
  ac_timeouts = [ 600, 600, 300 ];

  # 电池时：[白天, 夜晚, 事件期间] 的抓取间隔（单位：秒）
  batt_timeouts = [ 1200, 5400, 600 ];

  # 当检测到的亮度低于此值时, 认为摄像头被遮蔽, 取消本次检测
  shutter_threshold = 0.10

  # 笔记本合盖时暂停自动校准（强烈建议开启，防止合盖外接显示器时误判为极暗）
  pause_on_lid_closed = true;

  # 开盖时主动触发一次亮度校准
  capture_on_lid_opened = true;
};

@include "clight.d/daytime.conf"

gamma:
{
  # 白天与夜晚的屏幕色温 (K)
  temp = [ 6500, 5300 ];

  # 开启长过渡模式：在日出/日落期间（搭配 daytime 的 30 分钟 event_duration）
  # 色温会极其缓慢地发生渐变，让眼睛有一个自然适应的过程
  long_transition = true;

  # 使屏幕色温匹配屏幕背光亮度
  # 开启后, 屏幕色温随时间变化将失效
  # ambient_gamma = true;
};

inhibit:
{
  # 当有全屏视频播放或其他程序发出阻止休眠的请求时，
  # 自动暂停亮度和色温的调节，防止屏幕忽明忽暗影响观感
  inhibit_bl = true;

  # 阻止休眠
  inhibit_pm = true;
};

dpms:
{
  # 强制接管 DPMS 息屏时间，必须严格大于 dimmer 的时间
  # 这里设置为
  timeouts = [ -1, 3000 ];
};

dimmer:
{
  # AC 和 BATT 状态下，鼠标键盘无操作多久后屏幕变暗（单位：秒）
  timeouts = [ -2, 300 ];

  # 变暗后的亮度比例（0.2 即 20% 亮度）
  dimmed_pct = 0.2;

  # 变暗与恢复时的过渡时间（毫秒），1000ms 会有一种平缓的“呼吸感”
  trans_fixed = [ 1000, 1000 ];
};