[mgr]
# 面板比例
ratio = [1, 4, 3]
# 文件排序方式
sort_by = "natural"
sort_sensitive = true
sort_reverse = false
sort_dir_first = true
sort_translit = true

# 显示文件信息
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true

# 预览界面
[preview]
# 代码自动折行
wrap = "yes"
# tab宽度
tab_size = 2

# 图片预览
image_filter = "catmull-rom"
image_quality = 75

max_width = 1500
max_height = 3000

[input]
cursor_blink = true

[confirm]
delete = true

# 允许的文件打开方式
[opener]
edit = [
  { run = "${EDITOR:-nvim} %s", desc = "$EDITOR",      for = "unix", block = true },
  { run = "code %s",            desc = "code",         for = "windows", orphan = true },
  { run = "code -w %s",         desc = "code (block)", for = "windows", block = true },
]
# 批量重命名专用
bulk-rename = [
  { run = "nvim %s", desc = "nvim 批量重命名" },
]
play = [
  { run = "xdg-open %s1",    desc = "Play", for = "linux", orphan = true },
  { run = "open %s",         desc = "Play", for = "macos" },
  { run = 'start "" %s1',    desc = "Play", for = "windows", orphan = true },
  { run = "termux-open %s1", desc = "Play", for = "android" },
  { run = "mediainfo %s1; echo 'Press enter to exit'; read _", block = true, desc = "Show media info", for = "unix" },
  { run = "mediainfo %s1 & pause", block = true, desc = "Show media info", for = "windows" },
]
open = [
  { run = "xdg-open %s1",    desc = "Open", for = "linux" },
  { run = "open %s",         desc = "Open", for = "macos" },
  { run = 'start "" %s1',    desc = "Open", for = "windows", orphan = true },
  { run = "termux-open %s1", desc = "Open", for = "android" },
]
reveal = [
  { run = "xdg-open %d1",         desc = "Reveal", for = "linux" },
  { run = "open -R %s1",          desc = "Reveal", for = "macos" },
  { run = "explorer /select,%s1", desc = "Reveal", for = "windows", orphan = true },
  { run = "termux-open %d1",      desc = "Reveal", for = "android" },
  { run = "clear; exiv2 print %s1; echo 'Press enter to exit'; read _", desc = "Show EXIF", for = "unix", block = true },
]
extract = [
  { run = "7z x %s", desc = "Extract here (7z)" },
  { run = "ya pub extract --list %s", desc = "Extract here" },
]
compress = [
  { run = "zip -r %s.zip %s -x '*.git*' '*.venv*' '*node_modules*'", desc = "Comperss (zip)" }
]
download = [
  { run = "ya emit download --open %S", desc = "Download and open" },
  { run = "ya emit download %S",        desc = "Download" },
]

# 打开文件的策略
[open]
rules = [
  { url = "bulk-rename.txt", use = "bulk-rename" },
  # Folder
  { url = "*/", use = [ "edit", "open", "compress", "reveal" ] },
  # Text
  { mime = "text/*", use = [ "edit", "reveal" ] },
  # Image
  { mime = "image/*", use = [ "open", "reveal" ] },
  # Media
  { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
  # JSON
  { mime = "application/{json,ndjson}", use = [ "edit", "reveal" ] },
  { mime = "*/javascript", use = [ "edit", "reveal" ] },
  # Empty file
  { mime = "inode/empty", use = [ "edit", "reveal" ] },
  # Virtual file system
  { mime = "vfs/{absent,stale}", use = "download" },
  # Fallback
  { url = "*", use = [ "open", "reveal" ] },
]

[plugin]  
prepend_previewers = [  
  { mime = "text/csv", run = "duckdb" },
  { mime = "text/tab-separated-values", run = "duckdb" },
  { mime = "application/vnd.apache.parquet", run = "duckdb" },
  { mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", run = "duckdb" },
  { mime = "application/bittorrent", run = "torrent-preview" },
]

prepend_preloaders = [  
  { mime = "text/csv", run = "duckdb", multi = false },
  { mime = "text/tab-separated-values", run = "duckdb", multi = false },
]